# Análisis exploratorio de Sabores de Archipilego

In [6]:
# Librería 
import pandas as pd
import numpy as np 
import os

import sys
sys.path.append('..')
from src import soporte_analisis as sp

In [7]:
# Abrir archivos
ruta_carpeta = "../data" 
dataframes = sp.abrir_archivos_en_carpeta(ruta_carpeta)

In [8]:
# Visualizar archivos
for nombre, df in dataframes.items():
    print(f"\n🗂️ Archivo: {nombre}")
    display(df.head()) 
    df.info()
    print('DUPLICADOS')
    display(df.duplicated().sum())
    columnas_filtradas = [col for col in df.columns if df[col].nunique() < 15]
    if columnas_filtradas:
        print("\n📊 Valores únicos en columnas con menos de 10 valores únicos:")
        for col in columnas_filtradas:
            print(f"🔹 {col}: {df[col].unique()}")
    else:
        print("⚠️ No hay columnas con menos de 10 valores únicos.")
    
    print('_____________________________________________')

🗂️ Archivo: campaigns_data.csv

,Campaña ID,Tipo de Campaña,Fecha Inicio,Fecha Fin,Presupuesto,Impressions,Clics,Conversiones,ROI
0,1,Anuncios en Google,2025-01-06,2025-01-30,1245.29,39920,2383,217,2.06
1,2,Redes Sociales,2025-02-22,2025-02-27,1311.56,28414,877,41,3.73
2,3,Email Marketing,2025-01-16,2025-01-17,451.00,14057,571,29,2.25
3,4,Email Marketing,2025-02-24,2025-02-25,580.96,9478,628,44,2.39
4,5,Redes Sociales,2025-01-01,2025-01-06,1746.58,40902,738,27,2.59

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Campaña ID       50 non-null     int64
 1   Tipo de Campaña  50 non-null     object
 2   Fecha Inicio     50 non-null     object
 3   Fecha Fin        50 non-null     object
 4   Presupuesto      50 non-null     float64
 5   Impressions      50 non-null     int64
 6   Clics            50 non-null     int64
 7   Conversiones     50 non-null     int64
 8   ROI              50 non-null     float64
dtypes: float64(2), int64(4), object(3)
memory usage: 3.6+ KB
DUPLICADOS

np.int64(0)

📊 Valores únicos en columnas con menos de 10 valores únicos:
🔹 Tipo de Campaña: ['Anuncios en Google' 'Redes Sociales' 'Email Marketing']
_____________________________________________

🗂️ Archivo: clients_data.csv

,ID Cliente,Nombre,Edad,Género,Ubicación,Frecuencia de compra,Fecha de registro,Fuente de adquisición
0,1,Juan Carlos Mir-Benavides,63,M,Zaragoza,Una compra,2024-04-19,Redes sociales
1,2,Tito Sastre Campos,47,M,Barcelona,Recurrente,2023-08-03,Publicidad pagada
2,3,Agustina Roldan Enríquez,37,F,Santa Cruz de Tenerife,Una compra,2023-07-25,Búsqueda orgánica
3,4,Alejo Pou Mena,67,M,La Laguna,Ocasional,2023-12-11,Email marketing
4,5,Borja del Bayona,29,M,La Laguna,Ocasional,2023-08-05,Publicidad pagada

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID Cliente             100 non-null    int64
 1   Nombre                 100 non-null    object
 2   Edad                   100 non-null    int64
 3   Género                 100 non-null    object
 4   Ubicación              100 non-null    object
 5   Frecuencia de compra   100 non-null    object
 6   Fecha de registro      100 non-null    object
 7   Fuente de adquisición  100 non-null    object
dtypes: int64(2), object(6)
memory usage: 6.4+ KB
DUPLICADOS

np.int64(0)

📊 Valores únicos en columnas con menos de 10 valores únicos:
🔹 Género: ['M' 'F']
🔹 Frecuencia de compra: ['Una compra' 'Recurrente' 'Ocasional' 'VIP']
🔹 Fuente de adquisición: ['Redes sociales' 'Publicidad pagada' 'Búsqueda orgánica'
 'Email marketing' 'Recomendación' 'Evento gastronómico']
_____________________________________________

🗂️ Archivo: inventory_data.csv

,ID Producto,Nombre,SKU,Categoría,Proveedor,Stock Inicial,Stock Actual,Stock Mínimo,Stock Máximo,Costo Unitario,Precio Venta,Margen (%),Estado Stock,Fecha Reposición,Vida Útil (días)
0,1,Papas Negras de Canarias,Pf-001-PAP,Productos frescos,Agricultores Tenerife,95,33,40,120,6.75,10.95,62.22,Normal,NaN,30
1,2,Licor Plátano de Canarias,B-002-LIC,Bebidas,Destilerías Canarias,44,38,15,60,11.75,19.95,69.79,Normal,NaN,1095
2,3,Mojo Picón,Ayc-003-MOJ,Aceites y condimentos,Salsas Canarias,68,51,25,80,3.95,6.95,75.95,Normal,NaN,120
3,4,Dulce de Membrillo,Dym-004-DUL,Dulces y mermeladas,Conservas Isleñas,28,17,15,60,4.80,7.95,65.63,Normal,NaN,180
4,5,Miel de Palma,Dym-005-MIE,Dulces y mermeladas,Apicultores La Gomera,67,45,20,70,7.95,13.50,69.81,Normal,NaN,730

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID Producto       10 non-null     int64
 1   Nombre            10 non-null     object
 2   SKU               10 non-null     object
 3   Categoría         10 non-null     object
 4   Proveedor         10 non-null     object
 5   Stock Inicial     10 non-null     int64
 6   Stock Actual      10 non-null     int64
 7   Stock Mínimo      10 non-null     int64
 8   Stock Máximo      10 non-null     int64
 9   Costo Unitario    10 non-null     float64
 10  Precio Venta      10 non-null     float64
 11  Margen (%)        10 non-null     float64
 12  Estado Stock      10 non-null     object
 13  Fecha Reposición  0 non-null      float64
 14  Vida Útil (días)  10 non-null     int64
dtypes: float64(4), int64(6), object(5)
memory usage: 1.3+ KB
DUPLICADOS

np.int64(0)

📊 Valores únicos en columnas con menos de 10 valores únicos:
🔹 ID Producto: [ 1  2  3  4  5  6  7  8  9 10]
🔹 Nombre: ['Papas Negras de Canarias' 'Licor Plátano de Canarias' 'Mojo Picón'
 'Dulce de Membrillo' 'Miel de Palma' 'Gofio' 'Aceite de Oliva'
 'Queso Majorero' 'Almogrote' 'Vino Tinto Canario']
🔹 SKU: ['Pf-001-PAP' 'B-002-LIC' 'Ayc-003-MOJ' 'Dym-004-DUL' 'Dym-005-MIE'
 'Cyh-006-GOF' 'Ayc-007-ACE' 'Lyq-008-QUE' 'Ayc-009-ALM' 'B-010-VIN']
🔹 Categoría: ['Productos frescos' 'Bebidas' 'Aceites y condimentos'
 'Dulces y mermeladas' 'Cereales y harinas' 'Lácteos y quesos']
🔹 Proveedor: ['Agricultores Tenerife' 'Destilerías Canarias' 'Salsas Canarias'
 'Conservas Isleñas' 'Apicultores La Gomera' 'Molinos Gran Canaria'
 'Aceites Canarios S.L.' 'Quesería Fuerteventura' 'Salsas Gomeras'
 'Bodegas Tenerife']
🔹 Stock Inicial: [95 44 68 28 67 33 65 23 61]
🔹 Stock Actual: [33 38 51 17 45 27 12 50]
🔹 Stock Mínimo: [40 15 25 20 30]
🔹 Stock Máximo: [120  60  80  70  90 100  50 150]
🔹 Costo Unitario: [ 6.75 11.75  3.95  4.8   7.95  3.5   7.5   9.75  4.95 11.25]
🔹 Precio Venta: [10.95 19.95  6.95  7.95 13.5   6.5  12.95 15.95  8.5 ]
🔹 Margen (%): [62.22 69.79 75.95 65.63 69.81 85.71 72.67 63.59 71.72 77.33]
🔹 Estado Stock: ['Normal']
🔹 Fecha Reposición: [nan]
🔹 Vida Útil (días): [  30 1095  120  180  730  365   60   90]
_____________________________________________

🗂️ Archivo: sales_data.csv

        Fecha            Producto  Cantidad  Precio Unitario  Total Venta
0  2024-12-16  Dulce de Membrillo         2             9.19        18.38
1  2024-06-26  Vino Tinto Canario         2            21.04        42.08
2  2024-01-04     Aceite de Oliva         3            13.72        41.16
3  2024-08-04  Dulce de Membrillo         1             7.81         7.81
4  2024-04-07       Miel de Palma         1            10.00        10.00

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Fecha            200 non-null    object
 1   Producto         200 non-null    object
 2   Cantidad         200 non-null    int64
 3   Precio Unitario  200 non-null    float64
 4   Total Venta      200 non-null    float64
dtypes: float64(2), int64(1), object(2)
memory usage: 7.9+ KB
DUPLICADOS

np.int64(0)

📊 Valores únicos en columnas con menos de 10 valores únicos:
🔹 Producto: ['Dulce de Membrillo' 'Vino Tinto Canario' 'Aceite de Oliva'
 'Miel de Palma' 'Queso Majorero' 'Gofio' 'Mojo Picón' 'Almogrote'
 'Licor Plátano de Canarias' 'Papas Negras de Canarias']
🔹 Cantidad: [2 3 1 6]
_____________________________________________

🗂️ Archivo: satisfaction_data.csv

,ID Cliente,Producto,Calificación,Comentarios,Fecha Review,Comprador Verificado,Respuesta Vendedor,Compartido en Redes
0,62,Mojo Picón,5,"Excelente producto, receta tradicional. Volver...",2024-08-07,True,NaN,False
1,55,Papas Negras de Canarias,4,Bastante satisfecho/a con el Papas Negras de C...,2025-01-09,True,NaN,False
2,80,Mojo Picón,4,"Recomendable Mojo Picón, envase práctico.",2024-08-24,True,NaN,False
3,10,Papas Negras de Canarias,5,"Superó mis expectativas, buena conservación.",2025-03-13,True,NaN,False
4,12,Miel de Palma,5,"Miel de Palma de primera calidad, envase de ca...",2025-03-01,True,NaN,False

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID Cliente            100 non-null    int64
 1   Producto              100 non-null    object
 2   Calificación          100 non-null    int64
 3   Comentarios           100 non-null    object
 4   Fecha Review          100 non-null    object
 5   Comprador Verificado  100 non-null    bool
 6   Respuesta Vendedor    4 non-null      object
 7   Compartido en Redes   100 non-null    bool
dtypes: bool(2), int64(2), object(4)
memory usage: 5.0+ KB
DUPLICADOS

np.int64(0)

📊 Valores únicos en columnas con menos de 10 valores únicos:
🔹 Producto: ['Mojo Picón' 'Papas Negras de Canarias' 'Miel de Palma'
 'Vino Tinto Canario' 'Aceite de Oliva' 'Queso Majorero' 'Gofio'
 'Licor Plátano de Canarias' 'Almogrote' 'Dulce de Membrillo']
🔹 Calificación: [5 4 3 2]
🔹 Comprador Verificado: [ True False]
🔹 Respuesta Vendedor: [nan
 'Agradecemos su sinceridad. Estamos trabajando para mejorar y nos gustaría compensarle por esta experiencia.'
 'Gracias por sus comentarios. Nos tomamos muy en serio todas las opiniones para mejorar constantemente.'
 'Sentimos mucho su experiencia negativa. Hemos tomado nota y mejoraremos. ¿Podría contactarnos para ofrecerle una solución?']
🔹 Compartido en Redes: [False  True]
_____________________________________________

🗂️ Archivo: traffic_data.csv

,Fecha,Página de Aterrizaje,Duración (min),Tasa de Rebote,Fuente,Dispositivo
0,2025-01-27,Licor Plátano de Canarias,4.06,73.43,Pagado,Móvil
1,2025-01-15,Papas Negras de Canarias,1.71,67.77,Referidos,Móvil
2,2025-01-22,Gofio,3.23,62.45,Pagado,Desktop
3,2025-02-18,Gofio,6.87,54.00,Pagado,Desktop
4,2025-01-04,Gofio,2.28,82.74,Redes Sociales,Desktop

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Fecha                 150 non-null    object
 1   Página de Aterrizaje  150 non-null    object
 2   Duración (min)        150 non-null    float64
 3   Tasa de Rebote        150 non-null    float64
 4   Fuente                150 non-null    object
 5   Dispositivo           150 non-null    object
dtypes: float64(2), object(4)
memory usage: 7.2+ KB
DUPLICADOS

np.int64(0)

📊 Valores únicos en columnas con menos de 10 valores únicos:
🔹 Página de Aterrizaje: ['Licor Plátano de Canarias' 'Papas Negras de Canarias' 'Gofio'
 'Mojo Picón' 'Página de Inicio' 'Vino Tinto Canario' 'Aceite de Oliva'
 'Dulce de Membrillo' 'Miel de Palma' 'Almogrote' 'Queso Majorero']
🔹 Fuente: ['Pagado' 'Referidos' 'Redes Sociales' 'Orgánico' 'Email' 'Directo']
🔹 Dispositivo: ['Móvil' 'Desktop' 'Tablet']
_____________________________________________

# Cambiar los campos tipo fecha y visualizar como estan estructuradas por si necesitan cambios en el código de generacion de datos.

In [9]:
dataframes = {key: sp.convertir_columnas(df) for key, df in dataframes.items()}

In [10]:
# Intentar convertir columnas de fecha antes de filtrarlas
for key, df in dataframes.items():
    if df is not None and isinstance(df, pd.DataFrame):  # Verifica que df no sea None y sea un DataFrame
        for col in df.columns:
            if df[col].dtype == "object":  # Si la columna es tipo string
                try:
                    df[col] = pd.to_datetime(df[col], errors='coerce')  # Intenta convertir a datetime
                except:
                    pass  # Si falla, sigue con la siguiente

# Ver columnas de tipo fecha en cada DataFrame del diccionario
for key, df in dataframes.items():
    if df is not None and isinstance(df, pd.DataFrame):  # Verifica que df sea un DataFrame válido
        date_columns = [col for col in df.columns if pd.api.types.is_datetime64_any_dtype(df[col])]